

# Build settings
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - Gruntfile.js

sass:
    sass_dir: _sass
    style: compressed


collections:
  docs: 
    output: true
  work:
    output: true
    baseurl:
    
    
baseurl:
