

# Build settings
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - Gruntfile.js

sass:
    sass_dir: _sass
    style: compressed


collections:
  docs:
    output: true
  portfolio:
    output: true
    baseurl:
    
    
baseurl: https://dasdesigner.github.io/portfolio
